#!/usr/bin/env zsh
emulate -L zsh
cat <<'EOF'
Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: Mac14,2
      Chip: Apple M2
      Processor Name: arm64
      Memory: 16 GB
      System Version: macOS 15.6.1 (24G90)
EOF
exit 0

