#!/usr/bin/env zsh
emulate -L zsh
cat <<'EOF'
Mach Virtual Memory Statistics: (page size of 16384 bytes)
Pages free:                               1000.
Pages active:                             2000.
Pages inactive:                           3000.
EOF
exit 0

